### ISSUE TITLE
Beat test suite to submission

### ISSUE THREAD

**Issue by mcepl** [jenisys/parse_type#13]
This is necessary to beat tests to submission with Python 3.7.
[python3-fixes.patch](https://github.com/jenisys/parse_type/files/2860810/python3-fixes.patch.txt)

**Comment by jenisys** [comment]
You normally provide a pull-request for that (instead of patch-files).
**But why do think that your changes are necessary ?**

NOTE: `parse_type` should work with official `parse` module as well with the bundled copy of the `parse` module (since a few version of the `parse` module).

HINT: And your `import unittest` part will not get accepted (as long as python2.6 is supported). 
REASON: Works for me with my python version and platform is not acceptable; 
works on any platform w/ any python version is acceptable.

**Comment by mcepl** [comment]
For the attachment I am slightly sorry, but I am a maintainer of the Python universe in openSUSE. If I have clone of all packages we maintain, I would go crazy.

Ah, so it is not broken relative import, but you mean to use external library. Sorry, I misunderstood.

Yes, support for Python 2.6. OK.
